spring:
  profiles:
    active: mybatis
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: gyf123456
  cloud:
    stream:
      bindings:
        gaoyf:
          destination: gaoyf.exchange
          content-type: application/json

management:
  endpoints:
    web: #暴露所有web端点
      exposure:
        include: "*"
#      base-path: /aa #配置web访问端点的根目录

