server:
  port: 8001

spring:
  application:
    name: cloud-payment
  profiles:
    active: mybatis

eureka:
  instance:
    prefer-ip-address: true #以ip方式注册到注册中心 默认以主机名注册到注册中心
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka

