server:
  port: 7001
eureka:
  instance:
    hostname: eureka00
  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false #不开启服务检索功能
    service-url:
      defaultZone: http://eureka01:7001/eureka/