server:
  port: 8002

spring:
  application:
    name: cloud-order

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  instance:
    prefer-ip-address: true
    instance-id: order-service8002
    lease-renewal-interval-in-seconds: 30 #发送续约的间隔
    lease-expiration-duration-in-seconds: 90 #续约超时多少秒剔除服务
  client:
    service-url:
      #defaultZone: http://eureka01:7001/eureka,http://eureka00:7000/eureka
      defaultZone: http://eureka00:7000/eureka

logging:
  level:
    com.atgaoyf.springclouud.IPaymentService: debug
